#! /usr/bin/env perl
#
# Filename: forks
# Author: Olivier Sirol <czo@free.fr>
# License: GPL-2.0 (http://www.gnu.org/copyleft)
# File Created: 03 Dec 2019
# Last Modified: Tuesday 03 September 2024, 15:16
# $Id: forks,v 1.2 2024/06/11 19:51:30 czo Exp $
# Edit Time: 7:41:57
# Description:
#
#           Munin plugin
#           monitor the number of forks per second
#
# Copyright: (C) 2019-2024 Olivier Sirol <czo@free.fr>

# use strict;
use warnings;

## No warning or critical

##===================================================================##
## Main

if ( $ARGV[0] and $ARGV[0] eq "config" ) {
    print <<EOT;
graph_title Fork rate
graph_args --base 1000 -l 0
graph_vlabel forks / \${graph_period}
graph_category processes
graph_info This graph shows the number of forks (new processes started) per second.
forks.label forks
forks.type DERIVE
forks.min 0
forks.max 100000
forks.info The number of forks per second.
EOT
    exit 0;
}

$file = '/proc/stat';
open( FILE, "<$file" ) or die "ERROR: can't read $file: $!\n";
while (<FILE>) {
    chomp;
    if (/^processes\s+([0-9.]+)/) {
        $forks  = $1;
    }
}
close FILE;

print "forks.value $forks\n";

__END__
