#! /usr/bin/env perl
#
# Filename: forks
# Author: Olivier Sirol <czo@free.fr>
# License: GPL-2.0 (http://www.gnu.org/copyleft)
# File Created: 03 Dec 2019
# Last Modified: Monday 07 July 2025, 22:31
# $Id: forks,v 1.42 2025/07/07 22:31:08 czo Git $
# Edit Time: 8:00:50
# Description:
#
#       Munin plugin
#       monitor the number of forks per second
#
# Copyright: (C) 2019-2025 Olivier Sirol <czo@free.fr>

# use strict;
use warnings;

## No warning or critical

##===================================================================##
## Main

if ( $ARGV[0] and $ARGV[0] eq "config" ) {
    print <<EOT;
graph_title Fork rate
graph_args --base 1000 -l 0
graph_vlabel forks / \${graph_period}
graph_category processes
graph_info This graph shows the number of forks (new processes started) per second.
forks.label forks
forks.type DERIVE
forks.min 0
forks.max 100000
forks.info The number of forks per second.
EOT
    exit 0;
}

$file = '/proc/stat';
open( FILE, "<$file" ) or die "ERROR: can't read $file: $!\n";
while (<FILE>) {
    chomp;
    if (/^processes\s+([0-9.]+)/) {
        $forks = $1;
    }
}
close FILE;

print "forks.value $forks\n";

__END__
