#! /usr/bin/env perl
#
# Filename: if_err_br-lan
# Author: Olivier Sirol <czo@free.fr>
# License: GPL-2.0 (http://www.gnu.org/copyleft)
# File Created: 03 Dec 2019
# Last Modified: Tuesday 03 September 2024, 15:33
# $Id: if_err_eth0,v 1.5 2024/06/12 20:21:39 czo Exp $
# Edit Time: 9:10:32
# Description:
#
#           Munin plugin for if_[wildcard]
#           monitor traffic on network interfaces
#
# Copyright: (C) 2019-2024 Olivier Sirol <czo@free.fr>

# use strict;
use warnings;

## use or comment
$warning = 1;
## No critical

##===================================================================##
## Main

if ( $0 =~ /^(?:|.*\/)if_err_([^_]+)$/ ) {
    $INTERFACE = $1;
}

if ( $ARGV[0] and $ARGV[0] eq "config" ) {
    print <<EOT;
graph_order rcvd trans
graph_title Interface $INTERFACE errors
graph_args --base 1000
graph_vlabel packets in (-) / out (+) per \${graph_period}
graph_category network
graph_info This graph shows the amount of errors, packet drops, and collisions on the $INTERFACE network interface.
rcvd.label errors
rcvd.type COUNTER
rcvd.graph no
trans.label errors
trans.type COUNTER
trans.negative rcvd
rxdrop.label drops
rxdrop.type COUNTER
rxdrop.graph no
txdrop.label drops
txdrop.type COUNTER
txdrop.negative rxdrop
collisions.label collisions
collisions.type COUNTER
EOT
    if ( defined $warning ) {
        print <<EOT;
rcvd.warning $warning
trans.warning $warning
EOT
    }
    exit 0;
}

$rcvd       = 'U';
$trans      = 'U';
$rxdrop     = 'U';
$txdrop     = 'U';
$collisions = 'U';

$file = '/proc/net/dev';
open( FILE, "<$file" ) or die "ERROR: can't read $file: $!\n";
while (<FILE>) {
    chomp;
    if (/^\s*$INTERFACE:\s*(.*)$/) {
        $interface  = $1;
        @valuesif   = split( '\s+', $interface );
        $rcvd       = $valuesif[ 3 - 1 ];
        $trans      = $valuesif[ 11 - 1 ];
        $rxdrop     = $valuesif[ 4 - 1 ];
        $txdrop     = $valuesif[ 12 - 1 ];
        $collisions = $valuesif[ 14 - 1 ];
    }
}
close FILE;

print "rcvd.value $rcvd\n";
print "trans.value $trans\n";
print "rxdrop.value $rxdrop\n";
print "txdrop.value $txdrop\n";
print "collisions.value $collisions\n";

__END__
