#! /usr/bin/env perl
#
# Filename: load
# Author: Olivier Sirol <czo@free.fr>
# License: GPL-2.0 (http://www.gnu.org/copyleft)
# File Created: 03 Dec 2019
# Last Modified: Wednesday 04 September 2024, 10:51
# $Id: load,v 1.42 2024/09/04 10:51:07 czo Git $
# Edit Time: 7:09:07
# Description:
#
#           Munin plugin
#           monitor load average
#
# Copyright: (C) 2019-2024 Olivier Sirol <czo@free.fr>

# use strict;
use warnings;

## use or comment
$warning  = 10;
$critical = 120;

##===================================================================##
## Main

if ( $ARGV[0] and $ARGV[0] eq "config" ) {
    print <<EOT;
graph_title Load average
graph_args --base 1000 -l 0
graph_vlabel load
graph_scale no
graph_category system
graph_info The load average of the machine describes how many processes are in the run-queue (scheduled to run "immediately").
load.label load
load.info 5 minute load average"
EOT

    if ( defined $warning ) {
        print <<EOT;
load.warning $warning
load.critical $critical
EOT
    }
    exit 0;
}

$file = '/proc/loadavg';
open( FILE, "<$file" ) or die "ERROR: can't read $file: $!\n";
while (<FILE>) {
    chomp;
    ($load) = /^[0-9.]+\s+([0-9.]+)/;
    print "load.value $load\n";
}
close FILE;

__END__
