#! /usr/bin/env perl
#
# Filename: open_inodes
# Author: Olivier Sirol <czo@free.fr>
# License: GPL-2.0 (http://www.gnu.org/copyleft)
# File Created: 03 Dec 2019
# Last Modified: Tuesday 03 September 2024, 15:24
# $Id: open_inodes,v 1.3 2024/06/10 03:11:29 czo Exp $
# Edit Time: 7:42:37
# Description:
#
#           Munin plugin
#           monitor the number of open files in the system
#
# Copyright: (C) 2019-2024 Olivier Sirol <czo@free.fr>

# use strict;
use warnings;

## No warning or critical

##===================================================================##
## Main

# https://www.kernel.org/doc/Documentation/sysctl/fs.txt
$file = '/proc/sys/fs/inode-nr';
open( FILE, "<$file" ) or die "ERROR: can't read $file: $!\n";
while (<FILE>) {
    chomp;
    if (/([0-9.]+)\s+([0-9.]+)/) {
        $max  = $1;
        $free = $2;
    }
}
close FILE;

if ( $ARGV[0] and $ARGV[0] eq "config" ) {
    print <<EOT;
graph_title Inode table usage
graph_args --base 1000 -l 0
graph_vlabel number of open inodes
graph_category system
graph_info This graph monitors the Linux open inode table.
used.label open inodes
used.info The number of currently open inodes.
max.label inode table size
max.info The size of the system inode table. This is dynamically adjusted by the kernel.
EOT
    exit 0;
}

print "used.value " . ( $max - $free ) . "\n";
print "max.value $max\n";

__END__
