#! /usr/bin/env perl
#
# Filename: processes
# Author: Olivier Sirol <czo@free.fr>
# License: GPL-2.0 (http://www.gnu.org/copyleft)
# File Created: Dec 2014
# Last Modified: Thursday 13 June 2024, 15:18
# $Id: processes,v 1.5 2024/06/13 13:18:33 czo Exp $
# Edit Time: 7:35:31
# Description:
#
#           Munin plugin
#           monitor load average
#
# Copyright: (C) 2014-2024 Olivier Sirol <czo@free.fr>

# use strict;
use warnings;

##===================================================================##
## Main

if ( $ARGV[0] and $ARGV[0] eq "config" ) {
    print <<EOT;
graph_title Number of Processes
graph_args --base 1000 -l 0
graph_vlabel number of processes
graph_category processes
graph_info This graph shows the number of processes in the system.
processes.label processes
processes.info The current number of processes.
EOT
    exit 0;
}

## glob module may not be present...
# @nbproc = glob("/proc/[0-9]*");
# print "processes.value $#nbproc\n";

$nbproc = qx(echo /proc/[0-9]* | wc -w);
chomp $nbproc ;
print "processes.value $nbproc\n";
__END__
