#! /usr/bin/env perl
#
# Filename: processes
# Author: Olivier Sirol <czo@free.fr>
# License: GPL-2.0 (http://www.gnu.org/copyleft)
# File Created: Dec 2014
# Last Modified: Sunday 06 July 2025, 10:16
# $Id: processes,v 1.42 2025/07/06 10:16:19 czo Git $
# Edit Time: 8:01:51
# Description:
#
#           Munin plugin
#           monitor load average
#
# Copyright: (C) 2014-2025 Olivier Sirol <czo@free.fr>

# use strict;
use warnings;

## No warning or critical

##===================================================================##
## Main

if ( $ARGV[0] and $ARGV[0] eq "config" ) {
    print <<EOT;
graph_title Number of Processes
graph_args --base 1000 -l 0
graph_vlabel number of processes
graph_category processes
graph_info This graph shows the number of processes in the system.
processes.label processes
processes.info The current number of processes.
EOT
    exit 0;
}

## glob module may not be present...
# @nbproc = glob("/proc/[0-9]*");
# print "processes.value $#nbproc\n";

die "ERROR: can't read /proc\n" if ! -d '/proc';

$nbproc = qx(echo /proc/[0-9]* | wc -w);
chomp $nbproc;
print "processes.value $nbproc\n";

__END__
