#! /usr/bin/env perl
#
# Filename: uptime
# Author: Olivier Sirol <czo@free.fr>
# License: GPL-2.0 (http://www.gnu.org/copyleft)
# File Created: 03 Dec 2019
# Last Modified: Wednesday 04 September 2024, 10:52
# $Id: uptime,v 1.42 2024/09/04 10:52:02 czo Git $
# Edit Time: 7:15:50
# Description:
#
#           Munin plugin
#           Plugin to measure uptime.
#
# Copyright: (C) 2019-2024 Olivier Sirol <czo@free.fr>

# use strict;
use warnings;

## No warning or critical

##===================================================================##
## Main

if ( $ARGV[0] and $ARGV[0] eq "config" ) {
    print <<EOT;
graph_title Uptime
graph_args --base 1000 -l 0
graph_vlabel uptime in days
graph_category system
uptime.label uptime
uptime.draw AREA
uptime.info Uptime of this host
EOT
    exit 0;
}

$file = '/proc/uptime';
open( FILE, "<$file" ) or die "ERROR: can't read $file: $!\n";
# 407796.11 600573.58
while (<FILE>) {
    chomp;
    ($uptime) = /^([0-9.]+)/;
    printf "uptime.value %.2f\n",$uptime/86400;
}
close FILE;

__END__
