#! /bin/sh
#
# Filename: wireless
# Author: Olivier Sirol <czo@free.fr>
# License: GPL-2.0 (http://www.gnu.org/copyleft)
# File Created: 03 Dec 2019
# Last Modified: Thursday 13 June 2024, 12:33
# $Id: wireless,v 1.4 2024/06/11 20:03:40 czo Exp $
# Edit Time: 0:34:47
# Description:
#
#           munin plugin for wireless
#           copied from munilite
#
# Copyright: (C) 2019-2024 Olivier Sirol <czo@free.fr>

clean_fieldname() {
  echo "$@" | sed -e 's/^[^A-Za-z_]/_/' -e 's/[^A-Za-z0-9_]/_/g'
}

config_wireless() {
  interfaces=$(iwinfo 2> /dev/null | sed '/^[a-zA-Z]/!d; s/ .*//')
  radios=$(echo "${interfaces}" | sed '/-/d')
  for radio in ${radios}
  do
    echo "multigraph wireless_${radio}
graph_title WLAN ${radio} AP Statistics
graph_vlabel Strength (dBm)
graph_category network
graph_scale no
signal.label Signal
noise.label Noise"
  done
  for interface in ${interfaces}
  do
    echo "multigraph wireless_assoc_$(clean_fieldname "${interface}")
graph_title WLAN ${interface} associations
graph_vlabel Clients
graph_args --lower-limit 0
graph_category network
graph_scale no
clients.label Clients"
  done
}

fetch_wireless() {
  interfaces=$(iwinfo 2> /dev/null | sed '/^[a-zA-Z]/!d; s/ .*//')
  radios=$(echo "${interfaces}" | sed '/-/d')
  for radio in ${radios}
  do
    echo "multigraph wireless_${radio}"
    iwinfo "${radio}" info | sed -r 's/unknown/0 dBm/g; /Signal.*Noise/!d; s/^.* Signal: ([-0-9]+) dBm  Noise: ([-0-9]+) dBm/signal.value \1\nnoise.value \2/'
  done
  for interface in ${interfaces}
  do
    echo "multigraph wireless_assoc_$(clean_fieldname "${interface}")"
    echo "clients.value $(iwinfo "${interface}" assoc | grep -c SNR)"
  done
}

if [ "$#" -eq 1 -a X"$1" = "Xconfig" ]; then
    config_wireless
    exit 1
fi
fetch_wireless

