#! /bin/sh
#
# Filename: munin-node-configure
# Author: Olivier Sirol <czo@free.fr>
# License: GPL-2.0 (http://www.gnu.org/copyleft)
# File Created: 03 July 2025
# Last Modified: Friday 4 July 2025, 01:50
# $Id:$
# Edit Time: 0:00:57
# Description:
#
# Copyright: (C) 2025 Olivier Sirol <czo@free.fr>

if [ $(id -u) -ne 0 ]; then
  echo "ERROR: this script must be run as root"
  exit 1
fi

DIRNAME="$(dirname $(readlink -f $0))"
cd $DIRNAME || exit 42

case "X$(readlink /proc/1/exe 2>/dev/null)" in
  *systemd*)
    echo "System is using systemd."
    # Your systemd-specific command
    ;;
  *)
    echo "System is NOT using systemd."
    ;;
esac
