#! /usr/bin/env perl
#
# Filename: acpi
# Author: Olivier Sirol <czo@free.fr>
# License: GPL-2.0 (http://www.gnu.org/copyleft)
# File Created: 07 July 2025
# Last Modified: Sunday 15 February 2026, 18:33
# $Id: acpi,v 1.42 2026/02/15 18:33:34 czo Git $
# Edit Time: 1:13:35
# Description:
#
#       Munin plugin
#       monitor the temperature
#
#       Load the 'thermal' kernel module and the plugin gets the
#       thermal zones from /sys/class/thermal/thermal_zone*/
#
#       Orig (c) Nicolai Langfeldt (janl@linpro.no) 2006-11-13
#
# Copyright: (C) 2025, 2026 Olivier Sirol <czo@free.fr>

# use strict;
use warnings;

## No warning or critical

##===================================================================##
## Main
$thrm = '/sys/class/thermal';

opendir( $dh, $thrm ) or die "ERROR: can't read $thrm: $!\n";
@entries = readdir($dh);
closedir($dh);
@ATZ = grep { /^thermal_zone/ && -d "/sys/class/thermal/$_" } @entries;
@ATZ = map  { "/sys/class/thermal/$_" } @ATZ;

if ( $ARGV[0] and $ARGV[0] eq "config" ) {
    print <<EOT;
graph_title ACPI Thermal zone temperatures
graph_vlabel Celsius
graph_category sensors
graph_info This graph shows the temperature in different ACPI Thermal zones. If there is only one it will usually be the case temperature.
EOT
    foreach $zone ( sort @ATZ ) {
        if ( open( $fh, '<', "$zone/type" ) ) {
            my $type = <$fh>;
            chomp $type;
            close $fh;
            $zone_name = $zone;
            $zone_name =~ s,^.*/,,;
            print "${zone_name}.label $type\n";
        }
    }
    exit 0;
}

foreach $zone ( sort @ATZ ) {
    if ( open( my $fh, '<', "$zone/temp" ) ) {
        my $temp = <$fh>;
        chomp $temp;
        close $fh;
        $zone_name = $zone;
        $zone_name =~ s,^.*/,,;
        print "${zone_name}.value " . $temp / 1000 . "\n";
    }
}

__END__
