#! /usr/bin/env perl
#
# Filename: if_
# Author: Olivier Sirol <czo@free.fr>
# License: GPL-2.0 (http://www.gnu.org/copyleft)
# File Created: 03 Dec 2019
# Last Modified: Thursday 16 April 2026, 12:52
# $Id: if_,v 1.42 2026/04/16 12:52:03 czo Git $
# Edit Time: 8:44:02
# Description:
#
#           Munin plugin for if_[wildcard]
#           monitor traffic on network interfaces
#           from /proc/net/dev
#
# Copyright: (C) 2019-2026 Olivier Sirol <czo@free.fr>

# use strict;
use warnings;

## No warning or critical

##===================================================================##
## Main

if ( $0 =~ /^(?:|.*\/)if_(?!err_)(.+)$/ ) {
    $INTERFACE = $1;
}

if ( $ARGV[0] and $ARGV[0] eq "config" ) {
    print <<EOT;
graph_order down up
graph_title Interface $INTERFACE traffic
graph_args --base 1000
graph_vlabel bits in (-) / out (+) per \${graph_period}
graph_category network
graph_info This graph shows the traffic of the $INTERFACE network interface. Please note that the traffic is shown in bits per second, not bytes. IMPORTANT: Since the data source for this plugin use 32bit counters, this plugin is really unreliable and unsuitable for most 100Mb (or faster) interfaces, where bursts are expected to exceed 50Mbps. This means that this plugin is usuitable for most production environments. To avoid this problem, use the ip_ plugin instead.
down.label received
down.type DERIVE
down.min 0
down.graph no
down.cdef down,8,*
up.label bps
up.type DERIVE
up.min 0
up.negative down
up.cdef up,8,*
EOT

    foreach (qx(ethtool $INTERFACE 2>/dev/null)) {
        chomp;
        if (/^\s*Speed:\s*(\d+)+Mb\/s/) {
            $max = $1;
            print "up.info Max Speed: $max Mb/s\n";
            print "down.info Max Speed: $max Mb/s\n";
            $max = $max * 1024 * 1024;
            print "up.max $max\n";
            print "down.max $max\n";
        }
    }

    exit 0;
}

$down = 'U';
$up   = 'U';
$file = '/proc/net/dev';
open( FILE, "<$file" ) or die "ERROR: can't read $file: $!\n";
while (<FILE>) {
    chomp;
    if (/^\s*$INTERFACE:\s*(.*)$/) {
        $interface = $1;
        @valuesif  = split( '\s+', $interface );
        $down      = $valuesif[ 1 - 1 ];
        $up        = $valuesif[ 9 - 1 ];
    }
}
close FILE;

print "down.value $down\n";
print "up.value $up\n";

__END__
