#! /bin/sh
#
# Filename: munin-node-configure
# Author: Olivier Sirol <czo@free.fr>
# License: GPL-2.0 (http://www.gnu.org/copyleft)
# File Created: 03 July 2025
# Last Modified: Sunday 15 February 2026, 17:50
# $Id:$
# Edit Time: 1:03:50
# Description:
#
#             munin node configuration
#              - interfaces for all interface in /proc/net/dev
#              - systemd if OS has systmed
#              - acpi thermal
#
# Copyright: (C) 2025, 2026 Olivier Sirol <czo@free.fr>

## get the right path
DIRNAME="$(dirname $(readlink -f $0))"
echo $DIRNAME
cd $DIRNAME || exit 42

## interfaces
IF_NAMES=$(sed 's/^ *//; s/:.*$//; / /d; /^lo$/d' /proc/net/dev)
for INTER in $IF_NAMES; do
    # pas sur pour eth0.1
    # INTERRES=$(echo "$INTER" | sed -e 's/\./VLAN/' -e 's/\-/_/g')
    # echo $INTERRES
    echo "-> if_ and if_err_ $INTER OK"
    ln -sf $DIRNAME/if_ $DIRNAME/../plugins/if_$INTER
    ln -sf $DIRNAME/if_err_ $DIRNAME/../plugins/if_err_$INTER
done

## systemd
case "X$(readlink /proc/1/exe 2>/dev/null)" in
    *systemd*)
        echo "-> systemd OK"
        ln -sf $DIRNAME/systemd $DIRNAME/../plugins/
        ;;
esac

## acpi thermal
THERNB=$({ find /sys/class/thermal | grep "thermal_zone" | wc -l; } 2>/dev/null)
if [ ! "X$THERNB" = "X0" ]; then
    echo "-> acpi thermal OK"
    ln -sf $DIRNAME/acpi $DIRNAME/../plugins/
fi
